server:
  port: "8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  max_header_size: "1MB"

performance:
  max_procs: 0  # 0 = use all available CPUs
  memory_limit: "512MB"
  gc_percent: 100

database:
  host: "localhost"
  port: 5432
  user: "loan_user"
  password: "loan_password"
  dbname: "loan_db"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "1h"

redis:
  pool_size: 100
  min_idle_conns: 10
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"